### ISSUE TITLE
PHP cURL extension -- How to activate it?

### ISSUE THREAD

**Issue by asitemade4u** [rothgar/rpi-wordpress#1]
Hi,
Thank you for the amazing work on these images -- when used with your article, installing WP on a Raspberry was very simple.
I am using WordPress on the rPi to host MainWP, a platform to maintain, update and backup websites [https://mainwp.com/].
MainWP requires cURL extension activated on PHP to connect to remote websites.
I first tried to activate the PHP extension by accessing PHP ini in the PHP container but could not find any editor in the container [neither nano, nor vi].
Then I tried to set it up thru the PHP command line [php -d extensionextension=php_curl.dll] but then I got an error message saying the extension is not installed.

Please help.
Best,
Stephen

**Comment by rothgar** [comment]
There is a separate php container and it is not installed in the same container with the Caddy webserver. You'll probably need to install the plugin in the wordpress container but I'm not sure how you activate it.

You are welcome to install vi/nano in the wordpress container and try activating it there.
